import = [
    "~/.config/alacritty/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

option_as_alt = "Both"

[window]
padding.x = 10
padding.y = 10
opacity = 0.7
blur = true
# decorations = "Buttonless"

[scrolling]
history = 10000

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 18

[selection]
save_to_clipboard = true
